
name: Test Workflow

on:
  push:
    branches:
      - master

jobs:


  my_first_job:
    name: scan_find_vulnerability
    runs-on: ubuntu-latest
    steps:
      - name: Echo current branch
        run: echo "$(date):Current branch is ${{ github.ref_name }}"
      
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy-results.txt

      

   my_third_job:
    name: success workflow
    needs: my_first_job
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: shixiangqi/workshop-image:${{ github.sha }}

      - name: Sign image with a key
        run: cosign sign --key ${{ secrets.COSIGN_PRIVATE_KEY }} shixiangqi/workshop-image:${{ github.sha }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Notify Slack on success
        uses: slackapi/slack-github-action@v1.14.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          payload: |
            {
              "text": "CICD Pipeline Execution Report",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Build and Deployment Success",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:*\nFred"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation:*\nabc123"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:*\nfred@gmail.com"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Git Repository:*\n<https://github.com/ShiXiangqi01/Workshop.git|View Repository>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Docker Image:*\n<https://hub.docker.com/repository/docker/shixiangqi/workshop-image/general|View Image>"
                    }
                  ]
                }
              ]
            }

 