name: Test Workflow

on:
  push:
    branches:

jobs:
  my_first_job:
    name: Scan for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Vulnerability Scan with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'  # Corrected to 'fs' for filesystem scanning
          ignore-unfixed: true
          format: 'table'
          fail-on: 'HIGH'
          severity: 'HIGH'
          output: 'trivy-results.txt'

  my_second_job:
    name: fail workflow
    needs: my_first_job
    #if: ${{ failure() }}  # Correct conditional to capture failure from the first job
    runs-on: ubuntu-latest
    steps:

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          payload: |
            {
              "text": "Scan failed - Critical vulnerabilities found!",
              "attachments": [
                {
                  "title": "Failed trivy scan, see uploaded report",
                  "color": "#FF0000",
                  "fields": [
                    {
                      "title": "Total High/Critical Issues",
                      "value": "4 HIGH, 0 CRITICAL",
                      "short": true
                    }
                  ],
                  "footer": "CI/CD Pipeline | Scan Report"
                }
              ]
            }

      - name: Upload file to Slack
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: trivy-results.txt
          initial_comment: 'Post by slack-upload-file'

  
